continue_without_training: true
dataset_counter: 58
log_dir: Test
match_name: None
my_agent: random_agent
n_rounds: 2
play_parserscenario: classic
save_replay: false
save_stats: false
seed: 0
silence_errors: false
skip_frames: false
train: false
turn_based: false
update_interval: 0.1
