dataset_counter: 3
log_dir: Test
match_name: None
my_agent: random_agent
n_rounds: 20
play_parserscenario: classic
save_replay: true
save_stats: true
seed: 0
silence_errors: false
skip_frames: false
training: false
turn_based: false
update_interval: 0.1
