continue_without_training: true
dataset_counter: 16
log_dir: Test
match_name: None
my_agent: random_agent
n_rounds: 10
play_parserscenario: classic
save_replay: true
save_stats: true
seed: 0
silence_errors: false
skip_frames: false
training: true
turn_based: false
update_interval: 0.1
